kind: pipeline
name: pipeline-test

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  restore: true
  settings:
    mount:
    - ./node_modules
  volumes:
  - name: cache
    host: /tmp/cache

- name: install-dependencies
  image: node
  commands:
  - npm install

- name: build
  image: node
  commands:
  - npm run-script build

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: 
      from_secret: slack_channel
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
  when:
    status: [ success, failure ]

- name: publish
  image: plugins/scp
  when:
    target:
    - production
    event:
    - deploy

- name: rebuild-cache
  image: drillster/drone-volume-cache
  rebuild: true
  settings:
    mount:
    - ./node_modules
    volumes:
    - name: cache
      host: /tmp/cache