kind: pipeline
name: pipeline-test

steps:
- name: test
  image: busybox
  commands:
  - echo "success"

- name: build
  image: node
  commands:
  - npm install
  - npm run-script build

- name: notify
  image: plugins/slack
  when:
    status:
    - failure

- name: publish
  image: plugins/scp
  when:
    target:
    - production
    event:
    - deploy
