import React from 'react';
import Typography from 'material-ui/Typography';
import Button from 'material-ui/Button';
import Table, { TableBody, TableCell, TableHead, TableRow } from 'material-ui/Table';
import Grid from 'material-ui/Grid';
import Toolbar from 'material-ui/Toolbar';
import Paper from 'material-ui/Paper';
import Drawer from 'material-ui/Drawer';
import AppBar from 'material-ui/AppBar';
import { CircularProgress } from 'material-ui/Progress';

import ExtensionStateCompleteIcon from 'material-ui-icons/CheckCircle';
import InputField from 'components/Form/input-field';

import { graphql, gql } from 'react-apollo';
import validatorjs from 'validatorjs';
import MobxReactForm from 'mobx-react-form';

import styles from './style.module.css';
import DockerBuilder from './DockerBuilder';

const DEFAULT_EXTENSION = {
  id: -1,
  extensionSpec: {
    type: '',
  },
  formSpecValues: `{ "test": "1" }`
}

const DEFAULT_EXTENSION_SPEC = {
  id: -1,
}

@graphql(gql`
mutation CreateExtension ($projectId: String!, $extensionSpecId: String!, $formSpecValues: [KeyValueInput!]!) {
    createExtension(extension:{
      projectId: $projectId,
      extensionSpecId: $extensionSpecId,
      formSpecValues: $formSpecValues,
    }) {
        id
    }
}
`, { name: "createExtension" })

@graphql(gql`
mutation UpdateExtension ($id: String, $projectId: String!, $extensionSpecId: String!, $formSpecValues: [KeyValueInput!]!) {
    updateExtension(extension:{
      id: $id,
      projectId: $projectId,
      extensionSpecId: $extensionSpecId,
      formSpecValues: $formSpecValues,
    }) {
        id
    }
}
`, { name: "updateExtension" })




export default class Extensions extends React.Component {

  constructor(props){
    super(props)
    this.state = {
      addedExtensionsDrawer: {
        open: false,
        text: 'Edit',
        currentExtension: DEFAULT_EXTENSION,
      },
      availableExtensionsDrawer: {
        open: false,
        text: 'Add',
        currentExtensionSpec: DEFAULT_EXTENSION_SPEC,
      },
	  extensionFormSpecIsAutoGenerated: false,
    }
  }

  isAddedExtensionSelected(id){
    return this.state.addedExtensionsDrawer.currentExtension.id === id;
  }

  isAvailableExtensionSelected(id){
    return this.state.availableExtensionsDrawer.currentExtensionSpec.id === id;
  }

  handleAddedExtensionClick(event, extension){
    let addedExtensionsDrawer = this.state.addedExtensionsDrawer
    addedExtensionsDrawer.currentExtension = extension
    addedExtensionsDrawer.open = true

    let availableExtensionsDrawer = this.state.availableExtensionsDrawer
    availableExtensionsDrawer.open = false

    this.setState({
      drawerText: 'Edit',
      addedExtensionsDrawer: addedExtensionsDrawer,
      availableExtensionsDrawer: availableExtensionsDrawer,
      currentExtension: extension
    })
  }

  handleCloseAddedExtensionsDrawer(){
    let addedExtensionsDrawer = this.state.addedExtensionsDrawer
    addedExtensionsDrawer.open = false

    this.setState({
      addedExtensionsDrawer: addedExtensionsDrawer
    })
  }



  handleAvailableExtensionClick(event, extensionSpec){
    let availableExtensionsDrawer = this.state.availableExtensionsDrawer
    availableExtensionsDrawer.currentExtensionSpec = extensionSpec
    availableExtensionsDrawer.open = true

    let addedExtensionsDrawer = this.state.addedExtensionsDrawer
    addedExtensionsDrawer.open = false

	let extensionFormSpecIsAutoGenerated = true

	if(extensionSpec.component === "DockerBuilderView"){
		extensionFormSpecIsAutoGenerated = false
	}

    this.setState({
      drawerText: 'Add',
      addedExtensionsDrawer: addedExtensionsDrawer,
      availableExtensionsDrawer: availableExtensionsDrawer,
      currentExtension: extensionSpec,
	  extensionFormSpecIsAutoGenerated: extensionFormSpecIsAutoGenerated,
    })
  }

  handleCloseAvailableExtensionsDrawer(){
    let availableExtensionsDrawer = this.state.availableExtensionsDrawer
    availableExtensionsDrawer.open = false

    this.setState({
      availableExtensionsDrawer: availableExtensionsDrawer
    })
  }

  onSuccessAddExtension(form){
    console.log('onSuccessAddExtension')
    console.log(form)
	var self = this

	console.log(this.availableExtensionsForm.values())
    const convertedFormSpecValues = Object.keys(this.availableExtensionsForm.values()).map(function(key, index) {
        return {
            'key': key,
            'value': self.availableExtensionsForm[key]
        }
    })

	console.log(convertedFormSpecValues, this.props.project.id, this.state.availableExtensionsDrawer.currentExtensionSpec)

    this.props.createExtension({
      variables: {
        'projectId': this.props.project.id,
        'extensionSpecId': this.state.availableExtensionsDrawer.currentExtensionSpec.id,
        'formSpecValues': convertedFormSpecValues,
      }
    }).then(({ data }) => {
      console.log(data)
    }).catch(error => {
      console.log(error)
    })
  }

  onErrorAddExtension(form){
    console.log('onErrorAddExtension')
    console.log(form)
  }

  handleAddExtension(extension, event){
    console.log('handleAddExtension', extension)
    if(this.availableExtensionsForm){
      this.availableExtensionsForm.onSubmit(event, { onSuccess: this.onSuccessAddExtension.bind(this), onError: this.onErrorAddExtension.bind(this) })
    }
  }

  convertKVToJson(kvArr){
	let obj = {}
	kvArr.forEach(function(kv){
		obj[kv.key] = kv.value
	})
	return obj
  }

  renderFormSpecFromExtensionSpec(extensionSpec){
    console.log('renderFormSpecFromExtensionSpec', extensionSpec)
	let form = (<div></div>)

	switch(extensionSpec.component){
	case "DockerBuilderView":
		form = (<DockerBuilder
					project={this.props.project}
					extensionSpec={extensionSpec}
					createExtension={this.props.createExtension}
					handleClose={this.handleCloseAvailableExtensionsDrawer.bind(this)}
					viewType="edit" />)
		break;
	default:
		if(extensionSpec.id !== -1 ){

		  let plugins = {
			dvr: validatorjs,
		  }

		  let fields= extensionSpec.formSpec.map(function(kv){
			return kv.key
		  })

		  let rules = {}
		  extensionSpec.formSpec.map(function(kv){
			rules[kv.key] = kv.value
		  })

		  let labels = {}
		  extensionSpec.formSpec.map(function(kv){
			labels[kv.key] = kv.key
		  })

		  console.log(labels)
		  console.log(fields)
		  console.log(rules)

		  this.availableExtensionsForm = new MobxReactForm({ fields, rules, labels, plugins })
		  console.log(fields)
		  var self = this;
		  form = (
			<div>
			  <form>
				<Typography>
				  {fields.map(function(field){
					   return (
						 <InputField field={self.availableExtensionsForm.$(field)} />
					   )
					})}
				</Typography>
			  </form>
			</div>
		  )
		}
	}

	console.log(form)
	return form
  }

  renderFormSpecValues(extension){
		console.log(extension)
		let formSpecValues = JSON.parse(extension.formSpecValues)
		console.log(formSpecValues)
		formSpecValues = JSON.stringify(formSpecValues, null, 2)
		return (
			<Typography type="body2">
				{formSpecValues}
			</Typography>
		)
  }

  renderAddedExtensionView(extension){
      console.log(extension)
      let view = (<div></div>);

      if(extension.id !== -1){
          console.log(extension)
          switch(extension.extensionSpec.component){
              case "DockerBuilderView":
                  view = (
                    <DockerBuilder
                        project={this.props.project}
                        extensionSpec={extension.extensionSpec}
                        extension={extension}
                        updateExtension={this.props.updateExtension}
                        handleClose={this.handleCloseAddedExtensionsDrawer.bind(this)}
                        viewType="read" />)
                  break;
              default:
                view = (
                <div>
                    <Grid item xs={12}>
                        <Paper>
                            <Toolbar>
                                <div>
                                    <Typography type="title">
                                        Artifacts
                                    </Typography>
                                </div>
                            </Toolbar>
                            <Table bodyStyle={{ overflow: 'visible' }}>
                                <TableHead>
                                    <TableRow>
                                            <TableCell>
                                                Key
                                            </TableCell>
                                            <TableCell>
                                                Value
                                            </TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                {extension.artifacts.map(artifact => {
                                    return (
                                        <TableRow>
                                            <TableCell>
                                              {artifact.key}
                                            </TableCell>
                                            <TableCell>
                                              {artifact.value}
                                            </TableCell>
                                        </TableRow>
                                    )
                                })}
                                </TableBody>
                            </Table>
                        </Paper>
                    </Grid>
                </div>
                )
        }
      }
      return view
  }


  render() {
    const { project, extensionSpecs } = this.props;
    console.log(project)

    let addedExtensionsDeleteButton = "";

    if(this.state.addedExtensionsDrawer.currentExtension.id !== -1){
      addedExtensionsDeleteButton = (
        <Button
          disabled={this.state.loading}
          color="accent"
          onClick={()=>this.setState({ dialogOpen: true })}>
          Delete
        </Button>
      );
    }

    return (
      <div>
        <Grid container spacing={24}>
          <Grid item xs={12}>
            <Paper>
              <Toolbar>
                <div>
                  <Typography type="title">
                    Added Extensions
                  </Typography>
                </div>
              </Toolbar>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>
                      Name
                    </TableCell>
                    <TableCell>
                      Added
                    </TableCell>
                    <TableCell>
                      State
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {project.extensions.map(extension => {
                    const isSelected = this.isAddedExtensionSelected(extension.id);
                    let stateIcon = <CircularProgress size={25} />
                    if(extension.state === "complete"){
                        stateIcon = <ExtensionStateCompleteIcon />
                    }

                    return (
                      <TableRow
                        hover
                        onClick={event => this.handleAddedExtensionClick(event, extension)}
                        selected={isSelected}
                        tabIndex={-1}
                        key={extension.id}>
                        <TableCell> { extension.extensionSpec.name } </TableCell>
                        <TableCell> { new Date(extension.created).toDateString() }</TableCell>
                        <TableCell> { stateIcon } </TableCell>
                      </TableRow>
                    )
                  })}
                </TableBody>
              </Table>
            </Paper>
          </Grid>
          <Grid item xs={12}>
            <Paper>
              <Toolbar>
                <div>
                  <Typography type="title">
                    Available Extensions
                  </Typography>
                </div>
              </Toolbar>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>
                      Name
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {extensionSpecs.map(extensionSpec => {
                    let ignore = false

                    // check if this is already in added extensions
                    const addedExtensions = project.extensions.map(function(extension){
                      return extension.extensionSpec.name
                    })

                    if(addedExtensions.includes(extensionSpec.name)){
                      ignore = true
                    }

                    if(!ignore){
                      const isSelected = this.isAvailableExtensionSelected(extensionSpec.id);
                      return (
                        <TableRow
                          hover
                          onClick={event => this.handleAvailableExtensionClick(event, extensionSpec)}
                          selected={isSelected}
                          tabIndex={-1}
                          key={extensionSpec.id}>
                          <TableCell> { extensionSpec.name } </TableCell>
                        </TableRow>
                      )
                    } else {
                      return (
                        <div></div>
                      )
                    }
                  })}
                </TableBody>
              </Table>
            </Paper>
          </Grid>
        </Grid>

        <Drawer
          type="persistent"
          anchor="right"
          classes={{
            paper: styles.drawer
          }}
          open={this.state.addedExtensionsDrawer.open}
        >
            <div className={styles.createServiceBar}>
              <AppBar position="static" color="default">
                <Toolbar>
                  <Typography type="title" color="inherit">
                    {this.state.addedExtensionsDrawer.text} Extension
                  </Typography>
                </Toolbar>
              </AppBar>
              <div className={styles.drawerBody}>
                <Grid container spacing={24}>
                  <Grid item xs={12}>
                    <Typography>
                      Type: { this.state.addedExtensionsDrawer.currentExtension.extensionSpec.type}
                    </Typography>
                  </Grid>
                  <Grid item xs={12}>
                    {this.renderAddedExtensionView(this.state.addedExtensionsDrawer.currentExtension)}
                  </Grid>
                </Grid>
              </div>
            </div>
        </Drawer>

      <Drawer
          type="persistent"
          anchor="right"
          classes={{
            paper: styles.drawer
          }}
          open={this.state.availableExtensionsDrawer.open}
        >
            <div className={styles.createServiceBar}>
              <AppBar position="static" color="default">
                <Toolbar>
                  <Typography type="title" color="inherit">
                    {this.state.availableExtensionsDrawer.text} Extension
                  </Typography>
                </Toolbar>
              </AppBar>
              <div className={styles.drawerBody}>
                <Grid container spacing={24}>
                  <Grid item xs={12}>
                    <Typography type="subheading">
                      { this.state.availableExtensionsDrawer.currentExtensionSpec.name }
                    </Typography>
                  </Grid>
                  <Grid item xs={12}>
                    <Typography type="body2">
                      Type: { this.state.availableExtensionsDrawer.currentExtensionSpec.type }
                    </Typography>
                  </Grid>
                  <Grid item xs={12}>
                    {this.renderFormSpecFromExtensionSpec(this.state.availableExtensionsDrawer.currentExtensionSpec)}
                  </Grid>
				  {this.state.extensionFormSpecIsAutoGenerated &&
                  <Grid item xs={12}>
                    <Button raised color="primary" className={styles.rightPad}
                      onClick={(event) => this.handleAddExtension(this.state.availableExtensionsDrawer.currentExtensionSpec, event)}
                    >
                      add
                    </Button>
                    <Button color="primary"
                      onClick={this.handleCloseAvailableExtensionsDrawer.bind(this)}
                    >
                      cancel
                    </Button>
                  </Grid>
				  }
                </Grid>
              </div>
            </div>
        </Drawer>
      </div>
    )
  }
}
